### ISSUE TITLE
getallresponses(s[[1]]) gives a error, that NAs are not allowed in subscripted assignments.

### ISSUE THREAD

**Issue by aws6050** [cloudyr/Rmonkey#14]
Hi. Really excited about this package!

My issue is that I'm using Rmonkey on a variety of surveys of different types on a account and I always get the error below when I try to convert to a data frame. The lists returned by getresponses() look reasonable but both getallresponses(s[[1]]) and as.data.frame(g) all return the error below?

> getallresponses(s[[1]])
Error in names(responses)[names(responses) == unique_names[i]] <- paste0(unique_names[i],  
: 
  NAs are not allowed in subscripted assignments

**Comment by leeper** [comment]
Can you give me a little more information about the survey(s) you're working with? Does this happen on all of them? Or just some? Anything special about those that it fails on?

**Comment by aws6050** [comment]
Thank you! It was happening on all of the surveys that I tested. The
surveys in my account were ordinary and made by different people for
different purposes, so I can't think of anything special about them.

**Comment by leeper** [comment]
Okay, thanks. Can you give me the output from `traceback()` after the error occurs?

**Comment by aws6050** [comment]
Sure! As follows:
> traceback()
6: as.data.frame.sm_response(X[[i]], ...)
5: FUN(X[[i]], ...)
4: lapply(x, as.data.frame, details = details, stringsAsFactors = stringsAsFactors, 
       ...)
3: as.data.frame.sm_response_list(out, details = d)
2: as.data.frame(out, details = d)
1: getallresponses(s[[1]])

**Comment by rsmquest** [comment]
I am having the same issue using Rmonkey. Can see all question and answer ids, etc. using `str(d)` and `str(g)`, but struggling to coerce the data into a data frame - comes up with the same error as above when using `as.data.frame(g)`

> Error in names(responses)[names(responses) == unique_names[i]] <- paste0(unique_names[i],  : 
  NAs are not allowed in subscripted assignments

and trying `as.data.frame(d)` for good luck returns

> Error in as.data.frame.default(d) : 
  cannot coerce class ""sm_survey"" to a data.frame

any help??

**Comment by rsmquest** [comment]
edit: fixed by using `as.data.frame.ts(g)` rather than just `as.data.frame(g)`. Don't know how/why this works but pleased it has for me

**Comment by leeper** [comment]
@rsmquest Thanks for that. I will take a look and try to figure this out soon. Sorry for the trouble.

**Comment by carloserwin** [comment]
Hi, 

I am having the exact same problem, hope you can fix it ASAP. Following your code I tried to download the data base with the responses from a survey (this is all that I need) directly using the V3 of the API (Rmonkey uses V2) but it is really hard. After two days I still dont see the light!!! This is what I have been trying 

> api_key <- "SOME_LETTERS_AND_NUMBERS"
> oauth_token <- "EVEN_MORE_LETTERS_AND_NUMBERS"
> survey_id <- "SOME_NUMBERS"

> u <- paste("https://api.surveymonkey.net/v3/surveys/", survey_id, "/responses/bulk?api_key=",
           api_key, sep="")
> h <- add_headers(Authorization= paste("bearer", oauth_token), "Content-Type" = "application/json")
> out <- POST(url = u, config = h)
> stop_for_status(out)

Error: Not Found (HTTP 404)

Any help would be appreciated.

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
