### ISSUE TITLE
RMonkey data frame 

### ISSUE THREAD

**Issue by rsmquest** [cloudyr/Rmonkey#15]
I've downloaded data from SurveyMonkey using RMonkey into a data frame using the following code:

```
g <- getresponses(r, s[[1]])
g <- as.data.frame(g)
temp <- edit(g)
```
Using the data editor, I can see that the data obtained for each respondent is all in one column, as shown in this screengrab:

![screenshot](http://i.stack.imgur.com/az8MY.png)

I want to be able to have the question  ##as the header of the column and return all related answer IDs for each respondent within that column.

Was told that this sounds like a bug and to report it here.

**Comment by leeper** [comment]
Taking another look at this, it would appear that the issue is actually an error in `as.data.frame()` (probably same issue as in https://github.com/cloudyr/Rmonkey/issues/14). So you're looking at your initial `g` object rather than a data.frame representation thereof. Can you confirm that you're seeing an error during the `as.data.frame(g)` step, @rsmquest?

**Comment by rsmquest** [comment]
`class(g)` confirms `"data.frame"`, but get this error message when opening data editor: 

> Warning: class discarded from column ‘x’

**Comment by rsmquest** [comment]
Is there any way to manually separate these lists in the meantime? I've been trying all sorts of methods, but haven't had much success so far

**Comment by leeper** [comment]
@rsmquest The challenge is how the Survey Monkey API returns data values. It doesn't return raw data, but rather codes that correspond to data values stored in the "surveydetails" object. This means there's not really any useful way of looking at the value returned by `getresponses()` on its own.

The `as.data.frame()` method is actually quite convoluted. I have an idea for how to fix this, but it will unfortunately require some effort (and I won't be able to get to it until the end of this week).

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
