### ISSUE TITLE
Skipped Questions

### ISSUE THREAD

**Issue by kwhitely** [cloudyr/Rmonkey#18]
Using `getallresponses()` works great as long as all of the questions are answered.  If any questions are skipped I get the following error:  
```
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
```
I found that everything works if all questions are answered or if the same questions are skipped every time. In the latter case, only the answered questions show up in the data frame.  Would it be possible to make any skipped questions `NA` or `NULL`?

**Comment by leeper** [comment]
Thanks. Yes, there are actually many problems here (relatedly see #14). I am completely refactoring everything on a feature branch: https://github.com/cloudyr/Rmonkey/tree/df-fixes and will merge it in when complete. Sorry for the problems!

**Comment by kwhitely** [comment]
Thank you for the quick reply.  I also had the problem with #14, but was able to get around it by redesigning the survey to not have any subquestions.

**Comment by kwhitely** [comment]
leeper, I'm sure you have a better fix in mind, but I wanted to post this in case anyone is looking for a fix before your update.  I got it working by
```
Responses <- data.frame()
r <- respondentlist(surveys[[1]])
# get individual responses
g <- getresponses(r)
for(i in 1:length(g)){
     # coerce individual responses to df
     IndResp <- as.data.frame(g[[i]])
     # build df using bind_rows from dplyr package
     Responses <- bind_rows(Responses, IndResp)
}
```

**Comment by jsramos** [comment]
Thanks for creating the package. Unfortunately, I'm also running into this error, particularly when dealing with multiple option questions, since SM leaves an empty row to address the options.

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
