### ISSUE TITLE
getresponses logic version on GitHub vs 3.1

### ISSUE THREAD

**Issue by klittle314** [cloudyr/Rmonkey#19]
Working with a colleague today, we found what may be a bug in the new version of the getresponses function.

The new version at line 14-15 has a condition that is false if you pass the survey_id as a string, which appears to be permitted by the documentation (and was the case in version 0.3.1, where the logic checks if the survey parameter is of class "sm_survey" and if so overwrites the survey value with survey$survey_id.   But the logic in version 0.3.1 does not terminate if the survey parameter is not of class sm_survey.)

The new version of the function terminates with an error message to the user if you pass the survey parameter as a string.  Not sure how best to accommodate.   

Maybe revise else condition at line 17 of getresponses.R
``
`} else  {
 
 
     sval <- unique(unlist(lapply(respondents, `[`, "survey_id"))

     if(identical(survey,svals[1]) {

             survey <- survey

     } else {

             stop(" 'survey' does not match survey value in 'respondents')
     }`

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
