### ISSUE TITLE
createcollector fails when type='email'

### ISSUE THREAD

**Issue by iluv2sled** [cloudyr/Rmonkey#20]
using version 0.3.1, create collector succeeds when type='weblink', but fails when type='email.  The default example is failing:
createcollector(s[[1]]$survey_id, 'Emails', type='email', 
    recipients = list('first@example.com', 'second@example.com'),
    email_replyto='me@example.com', email_subject='Please complete a short survey!')

The error message is:
An error occurred: Value [u'52641325'] for field 'survey_id' is not of type string

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
