### ISSUE TITLE
Cannot register the redirect url

### ISSUE THREAD

**Issue by juyeongkim** [cloudyr/Rmonkey#21]
I was trying to register the redirect url as http://localhost:1410, but I get an error: "Invalid redirect URL".

**Comment by antaldaniel** [comment]
Same here.

**Comment by JakeRuss** [comment]
+1

**Comment by leeper** [comment]
Sorry about this. Unfortunately, this package is a temporary stasis period while I wait to refactor using Survey Monkey's new API (https://github.com/cloudyr/Rmonkey/issues/17), so I'm not sure how to address this. I'll try to work on it soon.
