### ISSUE TITLE
Omission in getrespondents.R

### ISSUE THREAD

**Issue by bcaessens** [cloudyr/Rmonkey#22]
Hi Thomas,

When using fields, like email, first_name, etc... in getrespondents, they are not returned in the output. I believe the oversight to be in the end of the getresponse.R function:

else {
        out <- lapply(content$data$respondents, function(x) {
            structure(list(respondent_id = x$respondent_id, survey_id = survey), class = "sm_respondent")
        })

As you can see, these fields are not included in creating the structure for the respondents. When I went through the steps in the function one-by-one, they were correctly requested in the body of the Json, and correctly returned in content$data...

You do check for their presence in the print function below. So my guess is that this is a small bug.

Just wanted to let you know. 

kind regards,
Bernie.

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
