### ISSUE TITLE
getallresponses returns error

### ISSUE THREAD

**Issue by SamPortnow** [cloudyr/Rmonkey#23]
getallresponses from the templates works fine, but not when I create my own survey. When I create my own survey, I get the error "Error in do.call(c, answerchoices) : second argument must be a list". I even created a survey from a template, removed all the the questions, and then added 1 multiple choice question, but still get the same error.

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
