### ISSUE TITLE
data.frame contains numbers instead of actual answers

### ISSUE THREAD

**Issue by dyeboi2** [cloudyr/Rmonkey#24]
Hey, when I pull the survey from survey monkey and store it in a data.frame instead of the answer that was actually provided a random number such as "165465461" is giving. Also the column heading aren't the actual questions. How can I fix this? @leeper

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
