### ISSUE TITLE
transition to SurveyMonkey API V3.0

### ISSUE THREAD

**Issue by klittle314** [cloudyr/Rmonkey#25]
We got a message about the deprecation of SM API 2.0 in 90 days.   Evidently, version 3.0 has some changes in methods as documented in [http://help.surveymonkey.com/articles/en_US/kb/Transitioning-to-SurveyMonkey-s-v3-API ].    That article suggests changes required in some of the Rmonkey functions, is that on your development path?

thanks!

**Comment by leeper** [comment]
Unfortunately, I do not have time to work on this, but [invite contributions](https://github.com/cloudyr/Rmonkey/issues/17) to get this working with the v3 API.
